apiVersion: v2
name: saleor-apps
description: A Helm chart for deploying Saleor Apps with shared Redis and DynamoDB support for Avatax. Includes the official Saleor apps by default and allows to add custom apps.
type: application
version: 0.4.10
appVersion: "1.0.0"
maintainers:
  - name: trieb.work
dependencies:
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
