apiVersion: v2
name: saleor-apps
description: A Helm chart for deploying Saleor Apps with shared Redis
type: application
version: 0.2.5
appVersion: "1.0.0"
maintainers:
  - name: trieb.work
dependencies:
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
