# Global settings
global:
  # Secret key used by all apps
  secretKey: ""
  # -- External Redis URL (if not using internal Redis)
  redisUrl: ""
  # -- Log level for all Saleor apps (can be 'info', 'debug', or 'trace')
  appLogLevel: "info"
  # -- Global TLS certificate configuration
  tls:
    # -- Enable global TLS certificate
    enabled: false
    # -- Existing TLS secret name to use for all ingress resources
    secretName: ""

# Redis configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: ""

# Common settings for all default marketplace apps
common:
  # set the APL name that should be used. Defaults to "redis", as we natively support that. Could be upstash or file as well
  apl: "redis"
  image:
    registry: ghcr.io
    repository: trieb-work/saleor-apps
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Marketplace configuration
# Provides a custom marketplace JSON endpoint for your Saleor apps. Access it at https://marketplace.apps.example.com/marketplace.json
marketplace:
  # Enable or disable the marketplace service
  enabled: true
  # Hostname where the marketplace JSON will be served
  hostname: marketplace.apps.example.com
  ingress:
    # Enable ingress for the marketplace service
    enabled: true
    # Additional annotations for the ingress (e.g., for cert-manager)
    annotations: {}
    className: ""
    tls:
      # Enable TLS for the marketplace ingress
      enabled: true
      # TLS secret name. Leave empty to use default: <release>-marketplace-tls
      secretName: ""

# Individual app configurations
apps:
  # Example of how to add your own custom app:
  # my-custom-app:
  #   enabled: false
  #   hostname: my-custom-app.apps.example.com
  #   port: 8000  # Port that your app listens on. Optional, defaults to 3000
  #   image:
  #     registry: ghcr.io  # Required
  #     repository: myorg/my-custom-app  # Required
  #     tag: v1.0.0  # Required
  #   manifestPath: /api/manifest  # Optional, defaults to /api/manifest
  #   extraEnvs:  # Optional, array of extra environment variables
  #   # Example:
  #   # extraEnvs:
  #   #   - name: MY_CUSTOM_ENV
  #   #     value: "custom-value"
  #   #   - name: SECRET_ENV
  #   #     valueFrom:
  #   #       secretKeyRef:
  #   #         name: my-secret
  #   #         key: secret-key
  #   ingress:
  #     enabled: true
  #     annotations: {}
  #     tls:
  #       enabled: true
  #       secretName: ""
  #   # Optional marketplace metadata
  #   marketplace:
  #     name: "My Custom App"  # Required if app is enabled
  #     logo:
  #       source: "https://example.com/logo.svg" # Optional
  #       color: "#000000" # Optional
  #     description:
  #       en: "My custom app description" # Optional
  #     integrations:  # Optional
  #       - name: "Integration Name"
  #         logo:
  #           light:
  #             source: "https://example.com/logo-light.svg"
  #           dark:
  #             source: "https://example.com/logo-dark.svg"
  #     privacyUrl: "https://example.com/privacy" # Optional
  #     supportUrl: "https://example.com/support" # Optional
  #     repositoryUrl: "https://github.com/myorg/my-custom-app" # Optional

  smtp:
    enabled: false
    hostname: smtp.apps.example.com
    extraEnvs: []
    port: 3000
    image:
      tag: "1.3.1"
    ingress:
      enabled: true
      annotations: {}
      className: ""
      tls:
        enabled: true
        secretName: ""  # Leave empty to use default name: <release>-smtp-tls

  search:
    enabled: false
    hostname: search.apps.example.com
    port: 3000
    image:
      tag: "1.23.1"
    ingress:
      enabled: true
      annotations: {}
      className: ""
      tls:
        enabled: true
        secretName: ""

  products-feed:
    enabled: false
    hostname: products-feed.apps.example.com
    port: 3000
    image:
      tag: "1.21.1"
    ingress:
      enabled: true
      annotations: {}
      className: ""
      tls:
        enabled: true
        secretName: ""

  app-avatax:
    enabled: false
    hostname: app-avatax.apps.example.com
    port: 3000
    image:
      tag: "1.13.1"
    ingress:
      enabled: true
      annotations: {}
      className: ""
      tls:
        enabled: true
        secretName: ""

  cms-v2:
    enabled: false
    hostname: cms-v2.apps.example.com
    port: 3000
    image:
      tag: "2.11.1"
    ingress:
      enabled: true
      annotations: {}
      className: ""
      tls:
        enabled: true
        secretName: ""

  klaviyo:
    enabled: false
    hostname: klaviyo.apps.example.com
    port: 3000
    image:
      tag: "1.13.1"
    ingress:
      enabled: true
      annotations: {}
      className: ""
      tls:
        enabled: true
        secretName: ""
