{{- range $appName, $appConfig := .Values.apps }}
{{- if $appConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "saleor-apps.fullname" $) $appName }}
  labels:
    {{- include "saleor-apps.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "saleor-apps.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $appName }}
  template:
    metadata:
      labels:
        {{- include "saleor-apps.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $appName }}
    spec:
      containers:
        - name: {{ $appName }}
          image: "{{ $appConfig.image.registry | default $.Values.common.image.registry }}/{{ $appConfig.image.repository | default (printf "%s/%s" $.Values.common.image.repository $appName) }}:{{ $appConfig.image.tag | default $.Values.common.image.tag }}"
          imagePullPolicy: {{ $.Values.common.image.pullPolicy }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor-apps.fullname" $ }}
                  key: secret-key
            - name: PORT
              value: {{ $appConfig.port | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: REDIS_URL
              value: {{ include "saleor-apps.redis.url" $ | quote }}
            - name: APL
              value: {{ $.Values.common.apl | quote }}
            - name: APP_LOG_LEVEL
              value: {{ $.Values.global.appLogLevel | quote }}
            {{- if eq $appName "app-avatax" }}
            {{- if (get $appConfig "dynamodb").enabled }}
            # DynamoDB environment variables for Avatax app
            - name: DYNAMODB_LOGS_TABLE_NAME
              value: {{ (get $appConfig "dynamodb").logsTableName | quote }}
            - name: DYNAMODB_LOGS_ITEM_TTL_IN_DAYS
              value: {{ (get $appConfig "dynamodb").logsItemTtlInDays | quote }}
            - name: AWS_REGION
              value: {{ (get $appConfig "dynamodb").region | quote }}
            - name: AWS_ENDPOINT_URL
              value: "http://{{ printf "%s-dynamodb" (include "saleor-apps.fullname" $) }}:8000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-dynamodb" (include "saleor-apps.fullname" $) }}
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-dynamodb" (include "saleor-apps.fullname" $) }}
                  key: secret-access-key
            {{- end }}
            {{- end }}
            {{- if $appConfig.extraEnvs }}
            {{- toYaml $appConfig.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $appConfig.port }}
              protocol: TCP
          {{- if $appConfig.probes | default $.Values.common.probes }}
          {{- with $appConfig.probes | default $.Values.common.probes }}
          livenessProbe:
            {{- if .path }}
            httpGet:
              path: {{ .path }}
              port: http
            {{- else }}
            tcpSocket:
              port: http
            {{- end }}
            initialDelaySeconds: {{ .initialDelaySeconds | default 10 }}
            periodSeconds: {{ .periodSeconds | default 10 }}
            timeoutSeconds: {{ .timeoutSeconds | default 5 }}
            successThreshold: {{ .successThreshold | default 1 }}
            failureThreshold: {{ .failureThreshold | default 3 }}
          readinessProbe:
            {{- if .path }}
            httpGet:
              path: {{ .path }}
              port: http
            {{- else }}
            tcpSocket:
              port: http
            {{- end }}
            initialDelaySeconds: {{ .initialDelaySeconds | default 5 }}
            periodSeconds: {{ .periodSeconds | default 10 }}
            timeoutSeconds: {{ .timeoutSeconds | default 5 }}
            successThreshold: {{ .successThreshold | default 1 }}
            failureThreshold: {{ .failureThreshold | default 3 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml $.Values.common.resources | nindent 12 }}
{{- end }}
{{- end }}
