{{- range $appName, $appConfig := .Values.apps }}
{{- if $appConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "saleor-apps.fullname" $) $appName }}
  labels:
    {{- include "saleor-apps.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "saleor-apps.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $appName }}
  template:
    metadata:
      labels:
        {{- include "saleor-apps.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $appName }}
    spec:
      containers:
        - name: {{ $appName }}
          image: "{{ $appConfig.image.registry | default $.Values.common.image.registry }}/{{ $appConfig.image.repository | default (printf "%s/%s" $.Values.common.image.repository $appName) }}:{{ $appConfig.image.tag | default $.Values.common.image.tag }}"
          imagePullPolicy: {{ $.Values.common.image.pullPolicy }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor-apps.fullname" $ }}
                  key: secret-key
            - name: PORT
              value: {{ $appConfig.port | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: REDIS_URL
              value: redis://{{ include "saleor-apps.fullname" $ }}-redis-master:6379
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor-apps.fullname" $ }}-redis
                  key: redis-password
          ports:
            - name: http
              containerPort: {{ $appConfig.port }}
              protocol: TCP
          resources:
            {{- toYaml $.Values.common.resources | nindent 12 }}
{{- end }}
{{- end }}
