{{- if (index .Values.apps "app-avatax") }}
{{- if (get (index .Values.apps "app-avatax") "enabled") }}
{{- if (get (index .Values.apps "app-avatax") "dynamodb").enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-dynamodb" (include "saleor-apps.fullname" .) }}
  labels:
    {{- include "saleor-apps.labels" . | nindent 4 }}
    app.kubernetes.io/component: dynamodb
type: Opaque
data:
  {{- if (get (get (index .Values.apps "app-avatax") "dynamodb") "accessKeyId") }}
  access-key-id: {{ (get (get (index .Values.apps "app-avatax") "dynamodb") "accessKeyId") | b64enc }}
  {{- else }}
  access-key-id: {{ "dynamodb-local" | b64enc }}
  {{- end }}
  {{- if (get (get (index .Values.apps "app-avatax") "dynamodb") "secretAccessKey") }}
  secret-access-key: {{ (get (get (index .Values.apps "app-avatax") "dynamodb") "secretAccessKey") | b64enc }}
  {{- else }}
  secret-access-key: {{ "dynamodb-local" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
