{{- range $appName, $appConfig := .Values.apps }}
{{- if and $appConfig.enabled $appConfig.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "saleor-apps.fullname" $) $appName }}
  labels:
    {{- include "saleor-apps.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
  {{- with $appConfig.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $appConfig.ingress.className }}
  ingressClassName: {{ $appConfig.ingress.className }}
  {{- end }}

  {{- if or $.Values.global.tls.enabled $appConfig.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $appConfig.hostname | quote }}
      {{- if $.Values.global.tls.enabled }}
      secretName: {{ $.Values.global.tls.secretName }}
      {{- else }}
      secretName: {{ $appConfig.ingress.tls.secretName | default (printf "%s-%s-tls" (include "saleor-apps.fullname" $) $appName) }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ $appConfig.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" (include "saleor-apps.fullname" $) $appName }}
                port:
                  number: {{ $appConfig.port }}
{{- end }}
{{- end }}
