{{- if and .Values.marketplace.enabled .Values.marketplace.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-marketplace
  labels:
    {{- include "saleor-apps.labels" . | nindent 4 }}
  {{- with .Values.marketplace.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.marketplace.ingress.className }}
  ingressClassName: {{ .Values.marketplace.ingress.className }}
  {{- end }}
  {{- if or .Values.global.tls.enabled .Values.marketplace.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.marketplace.hostname | quote }}
      {{- if .Values.global.tls.enabled }}
      secretName: {{ .Values.global.tls.secretName }}
      {{- else }}
      secretName: {{ default (printf "%s-marketplace-tls" .Release.Name) .Values.marketplace.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.marketplace.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-marketplace
                port:
                  name: http
{{- end }}
