apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-marketplace
  labels:
    {{- include "saleor-apps.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "saleor-apps.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: marketplace
