{{- if .Values.marketplace.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-marketplace
  labels:
    {{- include "saleor-apps.labels" . | nindent 4 }}
data:
  marketplace.json: |
    [
      {{- $first := true }}
      {{- if (index .Values.apps "products-feed").enabled }}
      {{- if not $first }},{{ end }}
      {
        "logo": {
          "source": "https://apps.saleor.io/apps/v2/saleor-apps/app-products-feed.svg",
          "color": "#7A96B0"
        },
        "name": {
          "en": "Product Feed"
        },
        "description": {
          "en": "Generate feeds consumed by Merchant Platforms"
        },
        "integrations": [
          {
            "name": "Google Merchant Center",
            "logo": {
              "light": {
                "source": "https://apps.saleor.io/apps/v2/google.svg"
              },
              "dark": {
                "source": "https://apps.saleor.io/apps/v2/google.svg"
              }
            }
          }
        ],
        "repositoryUrl": "https://github.com/saleor/apps",
        "manifestUrl": "https://{{ (index .Values.apps "products-feed").hostname }}/api/manifest",
        "privacyUrl": "https://saleor.io/legal/privacy/",
        "supportUrl": "https://saleor.io"
      }
      {{- $first = false }}
      {{- end }}
      {{- if (index .Values.apps "app-avatax").enabled }}
      {{- if not $first }},{{ end }}
      {
        "logo": {
          "source": "https://apps.saleor.io/apps/v2/saleor-apps/avatax.svg",
          "color": "#0000"
        },
        "name": {
          "en": "AvaTax"
        },
        "description": {
          "en": "AvaTax App allows dynamic tax calculations for orders and checkouts."
        },
        "integrations": [
          {
            "name": "AvaTax",
            "logo": {
              "light": {
                "source": "https://apps.saleor.io/apps/v2/avatax.svg"
              },
              "dark": {
                "source": "https://apps.saleor.io/apps/v2/avatax.svg"
              }
            }
          }
        ],
        "repositoryUrl": "https://github.com/saleor/apps",
        "manifestUrl": "https://{{ (index .Values.apps "app-avatax").hostname }}/api/manifest",
        "privacyUrl": "https://saleor.io/legal/privacy/",
        "supportUrl": "https://saleor.io"
      }
      {{- $first = false }}
      {{- end }}
      {{- if (index .Values.apps "cms-v2").enabled }}
      {{- if not $first }},{{ end }}
      {
        "logo": {
          "source": "https://apps.saleor.io/apps/v2/saleor-apps/cms-hub.svg",
          "color": "#27b476"
        },
        "name": {
          "en": "CMS"
        },
        "description": {
          "en": "CMS App is a multi-integration app that connects Saleor with popular Content Management Systems."
        },
        "integrations": [
          {
            "name": "Contentful CMS",
            "logo": {
              "light": {
                "source": "https://apps.saleor.io/apps/v2/contentful.png"
              },
              "dark": {
                "source": "https://apps.saleor.io/apps/v2/contentful.png"
              }
            }
          }
        ],
        "repositoryUrl": "https://github.com/saleor/apps",
        "manifestUrl": "https://{{ (index .Values.apps "cms-v2").hostname }}/api/manifest",
        "privacyUrl": "https://saleor.io/legal/privacy/",
        "supportUrl": "https://saleor.io"
      }
      {{- $first = false }}
      {{- end }}
      {{- if .Values.apps.search.enabled }}
      {{- if not $first }},{{ end }}
      {
        "logo": {
          "source": "https://apps.saleor.io/apps/v2/saleor-apps/search-hub.svg",
          "color": "#c73a3f"
        },
        "name": {
          "en": "Search"
        },
        "description": {
          "en": "Search App synchronizes product catalog with Algolia."
        },
        "integrations": [
          {
            "name": "Algolia",
            "logo": {
              "light": {
                "source": "https://apps.saleor.io/apps/v2/algolia.svg"
              },
              "dark": {
                "source": "https://apps.saleor.io/apps/v2/algolia.svg"
              }
            }
          }
        ],
        "repositoryUrl": "https://github.com/saleor/apps",
        "manifestUrl": "https://{{ .Values.apps.search.hostname }}/api/manifest",
        "privacyUrl": "https://saleor.io/legal/privacy/",
        "supportUrl": "https://saleor.io"
      }
      {{- $first = false }}
      {{- end }}
      {{- if .Values.apps.smtp.enabled }}
      {{- if not $first }},{{ end }}
      {
        "logo": {
          "source": "https://apps.saleor.io/apps/v2/smtp.svg",
          "color": "#fff"
        },
        "name": {
          "en": "SMTP"
        },
        "description": {
          "en": "SMTP App is a Saleor app that allows sending emails via SMTP protocol"
        },
        "integrations": [
          {
            "name": "SMTP",
            "logo": {
              "light": {
                "source": "https://apps.saleor.io/apps/v2/smtp.svg"
              },
              "dark": {
                "source": "https://apps.saleor.io/apps/v2/smtp.svg"
              }
            }
          }
        ],
        "repositoryUrl": "https://github.com/saleor/apps",
        "manifestUrl": "https://{{ .Values.apps.smtp.hostname }}/api/manifest",
        "privacyUrl": "https://saleor.io/legal/privacy/",
        "supportUrl": "https://saleor.io"
      }
      {{- $first = false }}
      {{- end }}
      {{- if (index .Values.apps "klaviyo").enabled }}
      {{- if not $first }},{{ end }}
      {
        "logo": {
          "source": "https://apps.saleor.io/apps/v2/saleor-apps/placeholder.svg",
          "color": "#3a56c7"
        },
        "name": {
          "en": "Klaviyo"
        },
        "description": {
          "en": "Klaviyo integration allows to send Saleor events to Klaviyo, where notifications can be sent to customers."
        },
        "integrations": [
          {
            "name": "Klaviyo",
            "logo": {
              "light": {
                "source": "https://apps.saleor.io/apps/v2/saleor-apps/app-klaviyo.svg"
              },
              "dark": {
                "source": "https://apps.saleor.io/apps/v2/saleor-apps/app-klaviyo.svg"
              }
            }
          }
        ],
        "repositoryUrl": "https://github.com/saleor/apps",
        "manifestUrl": "https://{{ (index .Values.apps "klaviyo").hostname }}/api/manifest",
        "privacyUrl": "https://saleor.io/legal/privacy/",
        "supportUrl": "https://saleor.io"
      }
      {{- $first = false }}
      {{- end }}
      {{- range $appName, $appConfig := .Values.apps }}
      {{- if and $appConfig.enabled $appConfig.marketplace }}
      {{- if not $first }},{{ end }}
      {
        "logo": {
          {{- if $appConfig.marketplace.logo }}
          "source": {{ $appConfig.marketplace.logo.source | quote }},
          "color": {{ $appConfig.marketplace.logo.color | quote }}
          {{- else }}
          "source": "https://apps.saleor.io/apps/v2/saleor-apps/placeholder.svg",
          "color": "#3a56c7"
          {{- end }}
        },
        "name": {
          "en": {{ $appConfig.marketplace.name | quote }}
        },
        {{- if $appConfig.marketplace.description }}
        "description": {
          "en": {{ $appConfig.marketplace.description.en | quote }}
        },
        {{- end }}
        {{- if $appConfig.marketplace.integrations }}
        "integrations": {{ $appConfig.marketplace.integrations | toJson }},
        {{- end }}
        {{- if $appConfig.marketplace.repositoryUrl }}
        "repositoryUrl": {{ $appConfig.marketplace.repositoryUrl | quote }},
        {{- end }}
        "manifestUrl": "https://{{ $appConfig.hostname }}{{ default "/api/manifest" $appConfig.manifestPath }}",
        {{- if $appConfig.marketplace.privacyUrl }}
        "privacyUrl": {{ $appConfig.marketplace.privacyUrl | quote }},
        {{- end }}
        {{- if $appConfig.marketplace.supportUrl }}
        "supportUrl": {{ $appConfig.marketplace.supportUrl | quote }}
        {{- else }}
        "supportUrl": "https://saleor.io"
        {{- end }}
      }
      {{- $first = false }}
      {{- end }}
      {{- end }}
    ]

{{- end }}
