apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saleor-apps.fullname" . }}
  labels:
    {{- include "saleor-apps.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.global.secretKey | b64enc }}
