# Test case for Saleor-apps with TLS completely disabled
global:
  secretKey: "test-secret-key"
  appLogLevel: "info"
  # Global TLS configuration disabled
  tls:
    enabled: false
    secretName: ""

# Redis configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: "test-redis-password"

# Marketplace configuration
marketplace:
  enabled: true
  hostname: marketplace-test-saleor.eu.fsn1.trwrk.xyz
  ingress:
    enabled: true
    annotations: {}
    tls:
      enabled: false
      secretName: ""

# Individual app configurations
apps:
  smtp:
    enabled: true
    hostname: smtp-test-saleor.eu.fsn1.trwrk.xyz
    ingress:
      annotations: {}
      tls:
        enabled: false
        secretName: ""
  
  products-feed:
    enabled: true
    hostname: products-feed-test-saleor.eu.fsn1.trwrk.xyz
    ingress:
      annotations: {}
      tls:
        enabled: false
        secretName: ""
  
  search:
    enabled: true
    hostname: search-test-saleor.eu.fsn1.trwrk.xyz
    ingress:
      annotations: {}
      tls:
        enabled: false
        secretName: ""
  
  app-avatax:
    enabled: true
    hostname: app-avatax-test-saleor.eu.fsn1.trwrk.xyz
    # Enable DynamoDB for Avatax
    dynamodb:
      enabled: true
      logsTableName: "avatax-client-logs"
      logsItemTtlInDays: 14
      region: "us-east-1"
      # Using dummy credentials for local DynamoDB
      accessKeyId: "dynamodb-local"
      secretAccessKey: "dynamodb-local"
    ingress:
      annotations: {}
      tls:
        enabled: false
        secretName: ""
