# Test case for Saleor-apps with local TLS (no global TLS)
global:
  secretKey: "test-secret-key"
  appLogLevel: "info"
  # Global TLS configuration disabled
  tls:
    enabled: false
    secretName: ""

# Redis configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: "test-redis-password"

# Marketplace configuration
marketplace:
  enabled: true
  hostname: marketplace-test-saleor.eu.fsn1.trwrk.xyz
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      enabled: true
      # This secretName should be used when global.tls.enabled is false
      secretName: "marketplace-specific-tls"

# Individual app configurations
apps:
  smtp:
    enabled: true
    hostname: smtp-test-saleor.eu.fsn1.trwrk.xyz
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        enabled: true
        secretName: "smtp-specific-tls"
  
  products-feed:
    enabled: true
    hostname: products-feed-test-saleor.eu.fsn1.trwrk.xyz
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        enabled: true
        secretName: "products-feed-specific-tls"
  
  search:
    enabled: true
    hostname: search-test-saleor.eu.fsn1.trwrk.xyz
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        enabled: true
        secretName: "search-specific-tls"
  
  app-avatax:
    enabled: true
    hostname: app-avatax-test-saleor.eu.fsn1.trwrk.xyz
    # Enable DynamoDB for Avatax
    dynamodb:
      enabled: true
      logsTableName: "avatax-client-logs"
      logsItemTtlInDays: 14
      region: "us-east-1"
      # Using dummy credentials for local DynamoDB
      accessKeyId: "dynamodb-local"
      secretAccessKey: "dynamodb-local"
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        enabled: true
        secretName: "avatax-specific-tls"
