global:
  secretKey: "test-secret-key-for-testing-purposes-only"
  tls:
    enabled: true
    secretName: "global-tls-secret"

ingress:
  enabled: true
  className: "nginx"
  api:
    enabled: true
    hosts:
      - host: saleor.example.com
        paths:
          - path: /graphql/
            pathType: Prefix
          - path: /thumbnail/
            pathType: Prefix
          - path: /.well-known/jwks.json
            pathType: Exact
    # Explicitly removing default TLS section
    tls: []

dashboard:
  enabled: true
