{{- if and .Values.storage.gcs.enabled .Values.storage.gcs.credentials.jsonKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saleor.fullname" . }}-gcs-credentials
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
type: Opaque
data:
  # Store the JSON key file content as a base64 encoded string
  credentials.json: {{ .Values.storage.gcs.credentials.jsonKey | b64enc | quote }}
{{- end }}
