{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saleor.fullname" . }}-postgresql-credentials
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.postgresPassword | default (randAlphaNum 32) | b64enc | quote }}
  user-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  replication-password: {{ .Values.postgresql.auth.replicationPassword | default (randAlphaNum 32) | b64enc | quote }}
  database-url: {{ printf "postgres://%s:%s@%s-postgresql-primary:5432/%s" .Values.postgresql.auth.username (.Values.postgresql.auth.password | default (randAlphaNum 32)) (include "saleor.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
{{- end }}
