{{- if .Values.storage.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saleor.fullname" . }}-s3-credentials
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.storage.s3.credentials.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.credentials.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.s3.credentials.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.credentials.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
