{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor.fullname" . }}-worker
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "saleor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if gt (int .Values.worker.replicaCount) 1 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - worker
              topologyKey: kubernetes.io/hostname
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["celery"]
          args: ["-A", "saleor.celeryconf", "worker", "--loglevel=info"]
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - celery -A saleor.celeryconf inspect ping -d celery@$HOSTNAME
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - celery -A saleor.celeryconf inspect ping -d celery@$HOSTNAME
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            {{- if include "saleor.readReplicaEnabled" . }}
            - name: settings
              mountPath: /app/saleor/settings.py
              subPath: settings.py
            {{- end }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor.fullname" . }}-secrets
                  key: database-url
            {{- if include "saleor.readReplicaEnabled" . }}
            - name: DATABASE_URL_REPLICA
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor.fullname" . }}-secrets
                  key: database-url-replica
            - name: DB_CONN_MAX_AGE
              value: {{ .Values.global.database.connMaxAge | quote }}
            {{- end }}
            {{- if .Values.global.jwtRsaPrivateKey }}
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor.fullname" . }}-secrets
                  key: jwt-private-key
            {{- end }}
            - name: DATABASE_CONNECTION_TIMEOUT
              value: {{ .Values.global.database.connectionTimeout | default "5" | quote }}
            - name: DATABASE_MAX_CONNECTIONS
              value: {{ .Values.global.database.maxConnections | default "150" | quote }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor.fullname" . }}-secrets
                  key: redis-url
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor.fullname" . }}-secrets
                  key: redis-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor.fullname" . }}-secrets
                  key: secret-key
            {{- include "saleor.s3Env" . | nindent 12 }}
            {{- with .Values.worker.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if include "saleor.readReplicaEnabled" . }}
        - name: settings
          configMap:
            name: {{ include "saleor.fullname" . }}-settings
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
