api:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"

dashboard:
  enabled: true
  replicaCount: 1

worker:
  enabled: true
  replicaCount: 1

postgresql:
  enabled: false

global:
  secretKey: "test-secret-key-123"
  database:
    primaryUrl: "postgres://saleor:password@external-db.example.com:5432/saleor"
    maxConnections: 150
    connectionTimeout: 5

redis:
  enabled: true
  auth:
    enabled: true
  architecture: standalone
