global:
  secretKey: "test-secret-key"

redis:
  enabled: false
  external:
    host: "my-redis.example.com"
    port: 6379
    username: "redis-user"
    password: "external-password"
    database: 2
    tls:
      enabled: true
