# Test case: External Redis with TLS and username/password authentication
global:
  secretKey: "test-secret-key"
  database:
    url: "postgres://postgres:postgres@localhost:5432/saleor"

redis:
  enabled: false
  external:
    host: "my-redis.example.com"
    port: 6379
    username: "redis-user"
    password: "external-password"
    tls:
      enabled: true
