# Test case: Redis with Sentinel architecture
global:
  secretKey: "test-secret-key"
  database:
    url: "postgres://postgres:postgres@localhost:5432/saleor"

redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
    password: "test-password"
  sentinel:
    enabled: true
    masterSet: "mymaster"
  replica:
    replicaCount: 2
